{
 "title": "OMG-GPU-DASHBOARD",
 "tags": [
  "NVIDIA",
  "GPU",
  "USAGE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "GPU-UTILIZATION",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"value\")) as power_usage FROM \"autogen\".\"dcgm_collectd_value\" WHERE (\"type\" = 'gpu_utilization' AND \"host\" =~ /-newgpu/ AND \"host\" !~ /-convert/ )AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU-PCIE-IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"value\")) as pcie_rx FROM \"autogen\".\"dcgm_collectd_value\" WHERE (\"type\" = 'pcie_rx_throughput' AND \"host\" =~ /-newgpu/ AND \"host\" !~ /-convert/ )AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"value\")) as pcie_tx FROM \"autogen\".\"dcgm_collectd_value\" WHERE (\"type\" = 'pcie_tx_throughput' AND \"host\" =~ /-newgpu/ AND \"host\" !~ /-convert/ )AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU-TEMP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"value\")) as power_usage FROM \"autogen\".\"dcgm_collectd_value\" WHERE (\"type\" = 'gpu_temp' AND \"host\" =~ /-newgpu/ AND \"host\" !~ /-convert/ )AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU-POWER-USAGE",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"value\")) as power_usage FROM \"autogen\".\"dcgm_collectd_value\" WHERE (\"type\" = 'fb_used' AND \"host\" =~ /-newgpu/ AND \"host\" !~ /-convert/ )AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU-POWER-USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"value\")) as power_usage FROM \"autogen\".\"dcgm_collectd_value\" WHERE (\"type\" = 'power_usage' AND \"host\" =~ /-newgpu/ AND \"host\" !~ /-convert/ )AND $timeFilter GROUP BY time(1m), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}